version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  app:
    build: ./app
    image: my-flask-app
    deploy:
      replicas: 3
    depends_on:
      - db
    volumes:
      - ./logs/app:/app/logs
    networks:
      - app_network

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./logs/db_logs:/var/log/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --log-error=/var/log/mysql/mysql-error.log --general_log=1 --general_log_file=/var/log/mysql/mysql-general.log --slow_query_log=1 --slow_query_log_file=/var/log/mysql/mysql-slow.log --long_query_time=2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
